-- AlterTable
ALTER TABLE `account` ADD COLUMN `adress` VARCHAR(191) NULL,
    ADD COLUMN `carryOver` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `lastReset` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `leaveBalance` INTEGER NOT NULL DEFAULT 12,
    ADD COLUMN `yearscareer` VARCHAR(191) NULL,
    MODIFY `role` VARCHAR(191) NOT NULL DEFAULT 'ADMIN';
